"""Report Writer Agent.

Assembles the final user-facing markdown report from everything the
preceding agents produced. No LLM call here - it's deterministic stitching
so the output is reproducible.
"""
from datetime import datetime
from state import AnalysisState
from utils.ratios import RATIO_LABELS, RATIO_CATEGORIES


def _fmt(val, as_pct: bool = False) -> str:
    if val is None:
        return "—"
    if as_pct:
        return f"{val * 100:.1f}%"
    return f"{val:.2f}"


PERCENT_RATIOS = {"gross_margin", "operating_margin", "net_margin",
                  "roa", "roe", "fcf_margin", "debt_to_assets"}


def _build_ratio_table(ratios_for_ticker: dict) -> str:
    """Make a markdown table of ratios x years for one ticker."""
    if not ratios_for_ticker:
        return "_No data._"

    years = sorted(ratios_for_ticker.keys(), reverse=True)
    header = "| Ratio | " + " | ".join(years) + " |"
    sep = "|" + "---|" * (len(years) + 1)

    rows = [header, sep]
    for category, keys in RATIO_CATEGORIES.items():
        rows.append(f"| **{category}** |" + " |" * len(years))
        for key in keys:
            label = RATIO_LABELS[key]
            as_pct = key in PERCENT_RATIOS
            cells = [_fmt(ratios_for_ticker[y].get(key), as_pct) for y in years]
            rows.append(f"| {label} | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def _build_comparison_table(comparison: dict) -> str:
    if not comparison:
        return ""
    rankings = comparison.get("rankings", {})
    snapshots = comparison.get("snapshots", {})
    tickers = list(snapshots.keys())
    if not tickers:
        return ""

    header = "| Ratio | " + " | ".join(tickers) + " | Best |"
    sep = "|" + "---|" * (len(tickers) + 2)
    rows = [header, sep]
    for key, r in rankings.items():
        as_pct = key in PERCENT_RATIOS
        cells = [_fmt(r["values"].get(t), as_pct) for t in tickers]
        rows.append(f"| {r['label']} | " + " | ".join(cells) + f" | **{r['best']}** |")
    return "\n".join(rows)


def report_writer_agent(state: AnalysisState) -> AnalysisState:
    log = state.get("log", [])
    tickers = state.get("tickers", [])
    raw = state.get("raw_data", {})
    quality = state.get("data_quality", {})
    ratios = state.get("ratios", {})
    comparison = state.get("comparison", {})
    insights = state.get("insights", "_No insights generated._")
    critique = state.get("critique", "")
    query = state.get("user_query", "")

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Header
    parts = [
        "# Financial Statement Analysis Report",
        f"*Generated {now}*",
        "",
        f"**Original request:** {query}",
        "",
        "---",
        "",
        "## Companies Analyzed",
        "",
    ]
    for t in tickers:
        info = raw.get(t, {}).get("info", {})
        name = info.get("longName", t)
        sector = info.get("sector", "Unknown")
        industry = info.get("industry", "Unknown")
        parts.append(f"- **{t}** — {name} *({sector} / {industry})*")
    parts.append("")

    # Data quality section
    parts += ["---", "", "## Data Quality Review", ""]
    parts.append("| Ticker | Completeness | Status | Issues |")
    parts.append("|---|---|---|---|")
    for t, q in quality.items():
        issues = "; ".join(q.get("issues", [])) or "None"
        parts.append(
            f"| {t} | {q['completeness']*100:.0f}% | "
            f"{'✅ Pass' if q['status'] == 'pass' else '❌ Fail'} | {issues} |"
        )
    parts.append("")

    # Insights
    parts += ["---", "", "## Analyst Insights", "", insights, ""]

    # Critic note
    if critique:
        parts += [
            "---", "",
            "## Critic Review",
            "",
            "_The critic agent reviewed the analyst's draft for accuracy and "
            "completeness before approval._",
            "",
            f"> {critique}",
            "",
        ]

    # Ratio tables per ticker
    parts += ["---", "", "## Detailed Ratios", ""]
    for t in tickers:
        if t in ratios:
            parts += [f"### {t}", "", _build_ratio_table(ratios[t]), ""]

    # Side-by-side comparison
    comp_table = _build_comparison_table(comparison)
    if comp_table:
        parts += [
            "---", "",
            "## Side-by-Side Comparison (Most Recent Year)",
            "",
            comp_table,
            "",
        ]
        win_tally = comparison.get("win_tally", {})
        if win_tally:
            parts.append("**Win tally** (number of ratios where each company ranks #1):")
            for t, w in sorted(win_tally.items(), key=lambda x: -x[1]):
                parts.append(f"- {t}: {w}")
            parts.append("")

    # Footer
    parts += [
        "---", "",
        "## Methodology",
        "",
        "This report was generated by a multi-agent workflow: Planner → "
        "Retriever → Validator → Ratio Calculator → Comparator → Analyst → "
        "Critic → Report Writer. Data: Yahoo Finance. Ratios are computed "
        "deterministically; narrative insights are LLM-generated and "
        "reviewed by a critic agent.",
        "",
        "*Not investment advice.*",
    ]

    report = "\n".join(parts)
    log.append(f"Report Writer: assembled final report ({len(report)} chars)")

    return {**state, "final_report": report, "log": log}
